## Project generator for the `mahanaim new` command.
##
## Generation is isolated from the CLI parser so it can be tested directly and
## reused by another command frontend later.

import std/[os, sequtils, strutils]

type ProjectSpec* = object
  name*: string
  root*: string

proc validProjectName*(name: string): bool =
  ## Restrict generated Nim identifiers to a predictable safe subset.
  if name.len == 0 or not (name[0].isAlphaAscii or name[0] == '_'):
    return false
  for character in name:
    if not (character.isAlphaNumeric or character == '_'):
      return false
  true

proc writeIfMissing(path, content: string) =
  ## Never overwrite user files: project generation must be recoverable.
  if fileExists(path):
    raise newException(IOError, "refusing to overwrite existing file: " & path)
  writeFile(path, content)

proc generateProject*(spec: ProjectSpec) =
  ## Create a deterministic vertical slice rather than an empty placeholder:
  ## configuration is visible, the generated app has one health route, and the
  ## generated test exercises the same Application.dispatch contract used by
  ## the framework suite. More features can be added without changing this
  ## module/package boundary.
  if not validProjectName(spec.name):
    raise newException(ValueError, "project name must be a valid Nim identifier")
  if dirExists(spec.root) and getFileInfo(spec.root).kind == pcDir:
    if toSeq(walkDir(spec.root)).len > 0:
      raise newException(IOError, "project directory is not empty: " & spec.root)
  else:
    createDir(spec.root)

  let srcDir = spec.root / "src"
  let testDir = spec.root / "tests"
  createDir(srcDir)
  createDir(testDir)
  writeIfMissing(spec.root / "README.md",
    "# " & spec.name & "\n\n" &
    "Generated by Mahanaim.\n\n" &
    "## Development\n\n" &
    "```text\n" &
    "nimble test\n" &
    "nimble build\n" &
    "```\n")
  writeIfMissing(spec.root / ".env.example",
    "MAHANAIM_ENV=development\n" &
    "MAHANAIM_HOST=127.0.0.1\n" &
    "MAHANAIM_PORT=8000\n")
  writeIfMissing(spec.root / ".gitignore",
    ".env\n" &
    "nimcache/\n" &
    "*.exe\n")
  writeIfMissing(spec.root / (spec.name & ".nimble"),
    "version = \"0.1.0\"\n" &
    "srcDir = \"src\"\n\n" &
    "bin = @[\"" & spec.name & "\"]\n\n" &
    "requires \"mahanaim >= 0.1.0\"\n" &
    "requires \"nim >= 2.2.0\"\n")
  writeIfMissing(srcDir / (spec.name & ".nim"),
    """## Generated application entry point.
##
## The starter deliberately wires one small model through the framework's
## metadata, migration, CRUD, admin, authentication, and documentation seams.
## Applications can replace these declarations while keeping the boundaries.

import std/[asyncdispatch]
import mahanaim

proc health(request: Request): Future[Response] {.async, gcsafe.} =
  ## Keep the handler capture-free; observability state belongs to Application.
  discard request
  return jsonResponse("{\"status\":\"ok\"}")

proc sliceMetadata(): ModelMetadata =
  ## One explicit metadata source feeds migration, validation, CRUD, and forms.
  result = newModelMetadata("Item", "items")
  result.addField(newModelField("id", modelInteger, primaryKey = true))
  result.addField(newModelField("title", modelString))

proc slicePolicy(): SecurityPolicy =
  ## Development defaults are explicit so generated tests can exercise the
  ## same CSRF/session boundary without relying on ambient environment state.
  result = defaultSecurityPolicy()
  result.csrfEnabled = true
  result.csrfSecret = "generated-app-csrf-secret-that-is-long-enough"
  result.csrfCookieSecure = false
  result.session.enabled = true
  result.session.cookieName = "mahanaim_session"
  result.session.secret = "generated-app-session-secret-that-is-long-enough"
  result.session.secureCookie = false

proc createApp*(config = loadConfig()): Application =
  ## Application construction owns the adapter and closes it with lifecycle.
  let policy = slicePolicy()
  let app = newApplication(config, policy)
  let adapter = newSqliteDatabaseAdapter()
  let metadata = sliceMetadata()
  let migration = migrationFromMetadata(metadata, "001_items")
  discard executeMigrationCommand(adapter, @[migration],
    parseMigrationCommand(["migrate"]))
  app.onShutdown(proc() {.gcsafe.} = adapter.close())

  let repository = newDatabaseRepository(metadata, adapter)
  let store = newDatabaseRepositoryResourceStore(repository)
  registerCrudRoutes(app, newCrudResource(metadata, store), "/items", "items")
  app.get("/health", "health", health)

  let accountStore = newInMemoryAccountCredentialStore()
  let hasher = newPbkdf2PasswordHasher(iterations = 10000)
  accountStore.addAccount(AccountCredential(subject: "admin-1",
    identifier: "admin@example.test", passwordHash: hasher.hashPassword(
      "admin-password"), enabled: true))
  let authentication = newAccountAuthentication(accountStore, hasher,
    policy.session, newInMemoryLoginThrottle())
  app.registerAccountAuthenticationRoutes(authentication)

  let adminRegistry = newAdminRegistry()
  proc authorize(request: Request): bool {.gcsafe.} =
    request.auth.authenticated and request.auth.subject == "admin-1"
  adminRegistry.registerAdminResource("items", "/admin/items", metadata,
    store, authorize, formPolicy = policy)
  registerAdminRoutes(app, adminRegistry)

  ## Route collection is intentionally performed at construction time so a
  ## generated application fails early if a route cannot be documented.
  let openApi = newOpenApiRegistry("Generated API", "0.1.0")
  discard openApi.collectRoutes(app.router)
  result = app

when isMainModule:
  ## A transport adapter can own the actual socket lifecycle later.
  discard createApp()
  echo "Generated application is configured."
""")
  writeIfMissing(testDir / "test_app.nim",
    """import std/[asyncdispatch, httpcore, json, tables, unittest]
import mahanaim
import """ & spec.name & """

suite "generated app vertical slice":
  test "generated app composes CRUD auth admin OpenAPI and lifecycle":
    let app = createApp()
    let client = newTestClient(app)
    let anonymousForm = waitFor client.get("/admin/items/new")
    check anonymousForm.status == Http403
    let csrf = client.cookies["mahanaim_csrf"]
    let csrfHeaders = [("x-csrf-token", csrf)]
    let login = waitFor client.post("/login",
      "{\"identifier\":\"admin@example.test\",\"password\":\"admin-password\"}",
      headers = csrfHeaders)
    check login.status == Http200
    check (waitFor client.get("/admin/items/new")).status == Http200
    let created = waitFor client.post("/items", "{\"title\":\"generated\"}",
      headers = csrfHeaders)
    check created.status == Http201
    check parseJson(created.body)["title"].getStr() == "generated"
    let listed = waitFor client.get("/admin/items")
    check listed.status == Http200
    check parseJson(listed.body)[0]["title"].getStr() == "generated"

    let openApi = newOpenApiRegistry("Generated API", "0.1.0")
    check openApi.collectRoutes(app.router) > 0
    check openApi.document()["paths"].hasKey("/items")
    check openApi.document()["paths"].hasKey("/admin/items")

    app.startup()
    let health = waitFor client.get("/health")
    check health.status == Http200
    check health.headers.hasKey("x-request-id")
    check healthResponse(app.observability).status == Http200
    app.shutdown()
    check not app.observability.ready
""")
