## Project generator for the `mahanaim new` command.
##
## Generation is isolated from the CLI parser so it can be tested directly and
## reused by another command frontend later.

import std/[os, sequtils, strutils]

type ProjectSpec* = object
  name*: string
  root*: string

proc validProjectName*(name: string): bool =
  ## Restrict generated Nim identifiers to a predictable safe subset.
  if name.len == 0 or not (name[0].isAlphaAscii or name[0] == '_'):
    return false
  for character in name:
    if not (character.isAlphaNumeric or character == '_'):
      return false
  true

proc writeIfMissing(path, content: string) =
  ## Never overwrite user files: project generation must be recoverable.
  if fileExists(path):
    raise newException(IOError, "refusing to overwrite existing file: " & path)
  writeFile(path, content)

proc generateProject*(spec: ProjectSpec) =
  ## Create the smallest runnable project with an explicit app entry point.
  if not validProjectName(spec.name):
    raise newException(ValueError, "project name must be a valid Nim identifier")
  if dirExists(spec.root) and getFileInfo(spec.root).kind == pcDir:
    if toSeq(walkDir(spec.root)).len > 0:
      raise newException(IOError, "project directory is not empty: " & spec.root)
  else:
    createDir(spec.root)

  let srcDir = spec.root / "src"
  let testDir = spec.root / "tests"
  createDir(srcDir)
  createDir(testDir)
  writeIfMissing(spec.root / "README.md", "# " & spec.name & "\n\nGenerated by Mahanaim.\n")
  writeIfMissing(spec.root / (spec.name & ".nimble"),
    "version = \"0.1.0\"\n" &
    "srcDir = \"src\"\n\n" &
    "requires \"mahanaim >= 0.1.0\"\n" &
    "requires \"nim >= 2.2.0\"\n")
  writeIfMissing(srcDir / (spec.name & ".nim"),
    "## Generated application entry point.\n" &
    "import mahanaim\n\n" &
    "let app = newApplication()\n" &
    "discard app\n")
  writeIfMissing(testDir / "test_app.nim",
    "import unittest\n\n" &
    "suite \"generated app\":\n" &
    "  test \"placeholder\":\n" &
    "    check true\n")
