## Project generator for the `mahanaim new` command.
##
## Generation is isolated from the CLI parser so it can be tested directly and
## reused by another command frontend later.

import std/[os, sequtils, strutils]

type ProjectSpec* = object
  name*: string
  root*: string

proc validProjectName*(name: string): bool =
  ## Restrict generated Nim identifiers to a predictable safe subset.
  if name.len == 0 or not (name[0].isAlphaAscii or name[0] == '_'):
    return false
  for character in name:
    if not (character.isAlphaNumeric or character == '_'):
      return false
  true

proc writeIfMissing(path, content: string) =
  ## Never overwrite user files: project generation must be recoverable.
  if fileExists(path):
    raise newException(IOError, "refusing to overwrite existing file: " & path)
  writeFile(path, content)

proc generateProject*(spec: ProjectSpec) =
  ## Create a deterministic vertical slice rather than an empty placeholder:
  ## configuration is visible, the generated app has one health route, and the
  ## generated test exercises the same Application.dispatch contract used by
  ## the framework suite. More features can be added without changing this
  ## module/package boundary.
  if not validProjectName(spec.name):
    raise newException(ValueError, "project name must be a valid Nim identifier")
  if dirExists(spec.root) and getFileInfo(spec.root).kind == pcDir:
    if toSeq(walkDir(spec.root)).len > 0:
      raise newException(IOError, "project directory is not empty: " & spec.root)
  else:
    createDir(spec.root)

  let srcDir = spec.root / "src"
  let testDir = spec.root / "tests"
  createDir(srcDir)
  createDir(testDir)
  writeIfMissing(spec.root / "README.md",
    "# " & spec.name & "\n\n" &
    "Generated by Mahanaim.\n\n" &
    "## Development\n\n" &
    "```text\n" &
    "nimble test\n" &
    "nimble build\n" &
    "```\n")
  writeIfMissing(spec.root / ".env.example",
    "MAHANAIM_ENV=development\n" &
    "MAHANAIM_HOST=127.0.0.1\n" &
    "MAHANAIM_PORT=8000\n")
  writeIfMissing(spec.root / ".gitignore",
    ".env\n" &
    "nimcache/\n" &
    "*.exe\n")
  writeIfMissing(spec.root / (spec.name & ".nimble"),
    "version = \"0.1.0\"\n" &
    "srcDir = \"src\"\n\n" &
    "bin = @[\"" & spec.name & "\"]\n\n" &
    "requires \"mahanaim >= 0.1.0\"\n" &
    "requires \"nim >= 2.2.0\"\n")
  writeIfMissing(srcDir / (spec.name & ".nim"),
    "## Generated application entry point.\n" &
    "## Keep application construction in one function so tests, CLI frontends,\n" &
    "## and a future network server all share the same route registration.\n\n" &
    "import std/asyncdispatch\n" &
    "import mahanaim\n\n" &
    "proc health(request: Request): Future[Response] {.async, gcsafe.} =\n" &
    "  discard request\n" &
    "  return jsonResponse(\"{\\\"status\\\":\\\"ok\\\"}\")\n\n" &
    "proc createApp*(config = loadConfig()): Application =\n" &
    "  ## The generated app keeps config injection explicit for tests and deploys.\n" &
    "  result = newApplication(config)\n" &
    "  result.get(\"/health\", \"health\", health)\n\n" &
    "when isMainModule:\n" &
    "  ## A transport adapter can own the actual socket lifecycle later.\n" &
    "  discard createApp()\n" &
    "  echo \"Generated application is configured.\"\n")
  writeIfMissing(testDir / "test_app.nim",
    "import std/[asyncdispatch, httpcore, unittest]\n" &
    "import mahanaim\n" &
    "import " & spec.name & "\n\n" &
    "suite \"generated app\":\n" &
    "  test \"health route uses the framework dispatch contract\":\n" &
    "    let response = waitFor createApp().dispatch(newRequest(\"GET\", \"/health\"))\n" &
    "    check response.status == Http200\n" &
    "    check response.body == \"{\\\"status\\\":\\\"ok\\\"}\"\n")
