## Direct httpx deployment adapter.
##
## This module is intentionally separate from the Prologue bridge. httpx owns
## its selector and listener lifecycle, while Mahanaim owns only request
## translation, application dispatch, response serialization, and WebSocket
## protocol handoff. Keeping that ownership boundary explicit lets Linux
## deployments choose httpx without exposing httpx types to core handlers.

when not defined(windows):
  import std/[asyncdispatch, httpcore, options, strutils, tables, uri]
  import pkg/httpx
  import ./application
  import ./core
  import ./router
  import ./websocket_adapter

  type
    HttpxServer* = ref object
      ## httpx does not expose a portable close API; the process or hosting
      ## supervisor owns termination while this object owns application hooks
      ## around the blocking server future.
      app*: Application
      settings*: httpx.Settings

  proc copyHeaders(headers: HttpHeaders): Table[string, string] =
    ## Normalize repeated wire fields into one comma-separated value. This is
    ## important for Accept and forwarding headers whose semantics depend on
    ## preserving every field occurrence at the adapter boundary.
    result = initTable[string, string]()
    for key, value in headers:
      let normalized = key.toLowerAscii()
      if result.hasKey(normalized):
        result[normalized].add(", " & value)
      else:
        result[normalized] = value

  proc parseCookies(headerValue: string): Table[string, string] =
    ## Keep cookie parsing local to the wire adapter. The core sees only the
    ## normalized name/value map and can remain independent of httpx syntax.
    result = initTable[string, string]()
    for item in headerValue.split(';'):
      let pieces = item.split('=', maxsplit = 1)
      if pieces.len == 2:
        result[pieces[0].strip()] = pieces[1].strip()

  proc toFrameworkRequest*(request: httpx.Request): core.Request =
    ## Convert the immutable httpx request view into the framework snapshot.
    ## httpx exposes the request target rather than a parsed URL object, so
    ## URI parsing belongs here and is performed exactly once.
    let target = request.path().get("/")
    let parsed = parseUri(target)
    let httpMethodName = if request.httpMethod().isSome:
      $request.httpMethod().get()
    else:
      "GET"
    result = newRequest(httpMethodName,
      if parsed.path.len == 0: "/" else: parsed.path,
      request.body().get(""))
    result.query = initTable[string, string]()
    for key, value in decodeQuery(parsed.query):
      result.query[key] = value
    result.headers = copyHeaders(request.headers().get(newHttpHeaders()))
    result.cookies = initTable[string, string]()
    if result.headers.hasKey("cookie"):
      result.cookies = parseCookies(result.headers["cookie"])

  proc responseHeaders(response: core.Response): string =
    ## httpx accepts raw response fields. Content-Length is generated by its
    ## send overload, so remove a handler-provided duplicate before writing.
    for key, value in response.headers:
      if key.toLowerAscii() != "content-length":
        result.add(key & ": " & value & "\c\L")

  proc handleRequest(server: HttpxServer,
                     request: httpx.Request): Future[void] {.async, gcsafe.} =
    ## Keep the callback as a thin adapter: translate once, dispatch once,
    ## and let the existing WebSocket transport own upgraded sockets.
    let frameworkRequest = toFrameworkRequest(request)
    let websocketRoute = server.app.router.findWebSocket(frameworkRequest.path)
    if websocketRoute.isSome:
      if frameworkRequest.httpMethod != "GET" or
          not isWebSocketUpgrade(frameworkRequest):
        request.send(Http426, "WebSocket upgrade required")
      else:
        await serveWebSocket(request, frameworkRequest, websocketRoute.get())
      return
    let response = await server.app.dispatch(frameworkRequest)
    request.send(response.status, response.body,
      some(response.body.len), responseHeaders(response))

  proc newHttpxServer*(app: Application, host = "127.0.0.1", port = 8000,
                       numThreads = 1): HttpxServer =
    ## Construct settings without starting a listener. Binding remains owned
    ## by httpx, making deployment configuration inspectable and testable.
    if app.isNil:
      raise newException(ValueError, "Application is required")
    if host.strip().len == 0:
      raise newException(ValueError, "httpx host is required")
    if port < 0 or port > 65535:
      raise newException(ValueError, "httpx port must be between 0 and 65535")
    if numThreads < 1:
      raise newException(ValueError, "httpx numThreads must be positive")
    HttpxServer(app: app, settings: httpx.initSettings(Port(port), host,
      numThreads = numThreads))

  proc runAsync*(server: HttpxServer): Future[void] {.async.} =
    ## httpx's runAsync owns its event-loop threads until the listener exits.
    ## Application startup/shutdown still surround that lifetime exactly once.
    if server.isNil:
      raise newException(ValueError, "httpx server is required")
    server.app.startup()
    try:
      let callback = proc(request: httpx.Request): Future[void]
          {.async, gcsafe.} =
        await handleRequest(server, request)
      await httpx.runAsync(callback, server.settings)
    finally:
      server.app.shutdown()

  proc run*(server: HttpxServer) =
    ## Synchronous deployment entry point for binaries that own the main loop.
    waitFor server.runAsync()
